# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: job_events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'job_events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10job_events.proto\x12\x0e\x61viary.jobs.v1\"p\n\x13PublishEventRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\x04\x12\x12\n\nevent_type\x18\x03 \x01(\t\x12\x14\n\x0cpayload_json\x18\x04 \x01(\t\x12\x12\n\nemitted_at\x18\x05 \x01(\t\"G\n\x15PublishEventsResponse\x12\x16\n\x0e\x61\x63\x63\x65pted_count\x18\x01 \x01(\x04\x12\x16\n\x0erejected_count\x18\x02 \x01(\x04\x32p\n\x0fJobEventIngress\x12]\n\rPublishEvents\x12#.aviary.jobs.v1.PublishEventRequest\x1a%.aviary.jobs.v1.PublishEventsResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLISHEVENTREQUEST']._serialized_start=36
  _globals['_PUBLISHEVENTREQUEST']._serialized_end=148
  _globals['_PUBLISHEVENTSRESPONSE']._serialized_start=150
  _globals['_PUBLISHEVENTSRESPONSE']._serialized_end=221
  _globals['_JOBEVENTINGRESS']._serialized_start=223
  _globals['_JOBEVENTINGRESS']._serialized_end=335
# @@protoc_insertion_point(module_scope)
